### PRODUCTION SPEED CONFIG - Target: <30 seconds
### Optimized for RTX 4090 to meet 300s cooldown windows
### Maintains >0.6 CLIP threshold while maximizing throughput

### Input
input:
prompt:
# Focused negative prompt - shorter for speed
negative_prompt: "ugly, blurry, low quality, deformed, bad anatomy, flat, 2d"
mesh:
elevation: 0
# SPEED: Reduced from 256 to 128 (4x faster VAE encoding)
ref_size: 128
density_thresh: 1

### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
mvdream: True
imagedream: False
stablediff: False
stable_zero123: False
zero123_xl: False

# QUALITY: Higher guidance_scale = better prompt adherence and quality
lambda_sd: 1
lambda_zero123: 0
guidance_scale: 100  # Increased from 50 for better quality (still faster than original 120)

warmup_rgb_loss: True

# CRITICAL SPEED OPTIMIZATION: Use batch_size=1 for MVDream's 4-view architecture
# Each batch generates 4 views (1 main + 3 MVDream additional views)
# batch_size=1 means 1 iteration = 4 views total for MVDream
batch_size: 1

# CRITICAL: 100 iterations for better quality and CLIP scores
# With optimized generation (~7 it/s), 100 iters = ~14s for 3D
# Total: ~4s SD + 1s BG + 14s 3D + 0.5s validation = ~20s (under 30s!)
iters: 100

anneal_timestep: True
iters_refine: 0  # Skip refinement for speed

# Tighter camera bounds = faster convergence
radius: 3.0
fovy: 49.1
min_ver: -20  # Reduced from -30
max_ver: 20   # Reduced from 30

load:
train_geo: False
invert_bg_prob: 0.5  # Keep randomness for robustness

### GUI
gui: False
force_cuda_rast: True  # SPEED: Force CUDA rasterization
H: 512  # Lower res for faster testing
W: 512

### Gaussian splatting - SPEED OPTIMIZED
num_pts: 4000  # Reduced from 8000 - faster initialization & densification
sh_degree: 1   # Changed from 0 to 1 to fix empty tensor issue

# Faster learning rates for quick convergence (adjusted for 100 iters)
position_lr_init: 0.0015    # Increased from 0.001
position_lr_final: 0.00005  # Increased from 0.00002
position_lr_delay_mult: 0.01  # Reduced from 0.02
position_lr_max_steps: 40  # 40% of 100 iters = 40

feature_lr: 0.015    # Increased from 0.01
opacity_lr: 0.08     # Increased from 0.05
scaling_lr: 0.008    # Increased from 0.005
rotation_lr: 0.008   # Increased from 0.005

# AGGRESSIVE densification schedule (adjusted for 100 iters)
percent_dense: 0.02  # Increased from 0.015 - more aggressive pruning
density_start_iter: 0
density_end_iter: 80  # Stop at 80% of total iters (80% of 100 = 80)
densification_interval: 20  # Densify every 20 iters (4 times: iter 20, 40, 60, 80)
opacity_reset_interval: 500  # Less frequent (won't trigger in 250 iters)
densify_grad_threshold: 0.015  # Higher threshold = less densification = faster

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2
