### PRODUCTION SPEED CONFIG - Target: <30 seconds
### Optimized for RTX 4090 to meet 300s cooldown windows
### Maintains >0.6 CLIP threshold while maximizing throughput

### Input
input:
prompt:
# Focused negative prompt - shorter for speed
negative_prompt: "ugly, blurry, low quality, deformed, bad anatomy, flat, 2d"
mesh:
elevation: 0
# SPEED: Reduced from 256 to 128 (4x faster VAE encoding)
ref_size: 128
density_thresh: 1

### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
mvdream: True
imagedream: False
stablediff: False
stable_zero123: False
zero123_xl: False

# QUALITY: Higher guidance_scale = better prompt adherence and quality
lambda_sd: 1
lambda_zero123: 0
guidance_scale: 100  # Increased from 50 for better quality (still faster than original 120)

warmup_rgb_loss: True

# CRITICAL SPEED OPTIMIZATION: Use batch_size=1 for MVDream's 4-view architecture
# Each batch generates 4 views (1 main + 3 MVDream additional views)
# batch_size=1 means 1 iteration = 4 views total for MVDream
batch_size: 1

# QUALITY OPTIMIZATION: 100 iterations to allow Gaussians to learn
# Target: ~34s total time (FLUX 26s + BG 1.5s + 3D ~40s + validation 0.5s)
# 100 iters needed for Gaussians to converge to meaningful features
# With pruning disabled, need more iterations to learn proper colors/positions
iters: 100

anneal_timestep: True
iters_refine: 0  # Skip refinement for speed

# Tighter camera bounds = faster convergence
radius: 3.0
fovy: 49.1
min_ver: -20  # Reduced from -30
max_ver: 20   # Reduced from 30

load:
train_geo: False
invert_bg_prob: 0.5  # Keep randomness for robustness

### GUI
gui: False
force_cuda_rast: True  # SPEED: Force CUDA rasterization
H: 512  # Lower res for faster testing
W: 512

### Gaussian splatting - QUALITY OPTIMIZED for competition
num_pts: 6000  # Increased from 4000 for better detail (competitive miners use 6000-8000)
sh_degree: 1   # Changed from 0 to 1 to fix empty tensor issue

# Standard DreamGaussian learning rates for 100 iterations
position_lr_init: 0.00016     # Standard value (was 0.002 - too high)
position_lr_final: 0.0000016  # Standard value (was 0.0001 - too high)
position_lr_delay_mult: 0.01
position_lr_max_steps: 40     # 40% of 100 iters = 40

feature_lr: 0.0025    # Standard value (was 0.015 - too high)
opacity_lr: 0.05      # Standard value (was 0.08 - too high)
scaling_lr: 0.005     # Standard value (was 0.008 - too high)
rotation_lr: 0.001    # Standard value (was 0.008 - way too high)

# DISABLED densification - keep all 6000 Gaussians to diagnose training
percent_dense: 1.0  # Never prune (100% kept)
density_start_iter: 999  # Never start
density_end_iter: 999  # Never end
densification_interval: 999  # Never trigger
opacity_reset_interval: 999  # Never reset
densify_grad_threshold: 999.0  # Never densify

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2
